### PR TITLE
 - Removed ClientRepository

### PR DESCRIPTION
**Pull request by sahiltalwar88**
- Updated Context to implement IContext interface to properly mask EF from the rest of the project
 - Now properly injecting dependencies (context) into controller
 - Updated routing
 - Updated Client
 - Updated js URIs

### CODE REVIEW

**Comment by LougeniaC64** [comment]
you're the best sahil!

**Comment by sahiltalwar88** [comment]
yayyyyyy

**Comment by LougeniaC64** [comment]
you're the WORST!!

**Comment by sahiltalwar88** [comment]
:(

**Pull request merged**
